Add connection state filter method
mullvad/pfctl-rs pull request #106
Opened 2024-06-28 07:56 UTC by dlon

Add `PfCtl::filter_states`, which can be used to individually inspect and remove connection states. The existing methods (`clear_states`, and `clear_interface_states`) are less only allow states associated with a given anchor or interface to be removed, so this one gives more control.

2024-07-02 06:44 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/106)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[`src/state.rs` line 15 at r1](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O0m9_xR1_eSTtf2dR_X:-O0m9_xR1_eSTtf2dR_Y:b-ebmfma) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0cae58767a64a3859cbf14f7a41842c46135ac82/src/state.rs#L15)):*
> ```XML
>     Ip(IpState),
>     /// Any connection state that could not be parsed
>     Raw(pfsync_state),
> ```

This publicly exposes a type from the `ffi` module. We can't do this. Everything related to the FFI and automatically generated bindings are *internal details* only.
___
*[`src/state.rs` line 32 at r1](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O0mAdetE_0FT0gD-355:-O0mAdeuCrMT9YG9_-GK:b6vxo6p) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0cae58767a64a3859cbf14f7a41842c46135ac82/src/state.rs#L32)):*
> ```XML
>         IpState::try_from(state)
>             .map(State::Ip)
>             .unwrap_or_else(|_| State::Raw(state))
> ```

Is there no field in `pfsync_state` that indicate what kind of state it is? Having it be raw just because it fails to parse as an IP state feels slightly off, but I don't know the PF internals around this.


<!-- Sent from Reviewable.io -->

2024-07-02 06:53 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/106)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[`src/lib.rs` line 344 at r1](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O0mBOSH7iL50amIDOGd:-O0mBOSH7iL50amIDOGe:b-h1sn2r) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0cae58767a64a3859cbf14f7a41842c46135ac82/src/lib.rs#L344)):*
I think the documentation would be clearer if it mentions that it *removes* states for which the filter returns `false`. Because that's the "action" that is taken in this method. Nothing actually happens to the states where the filter returns true, they are just ignored.

> Keep all states for which `filter` returns true. The rest are removed from PF.

?

Would also be nice if it mentions that if the function returns an error, some states *might* have been removed already.

> If an error is returned, all states except the last one for which the filter returned `false` has already been removed.


<!-- Sent from Reviewable.io -->

2024-07-23 11:49 UTC, faern reviewed
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/106)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @dlon)

___
*[`src/lib.rs` line 92 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UIUUN2Ga-qzfx1z4a:-O2UIUUO3VoagGXg_WBU:bisvqsh) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/lib.rs#L92)):*
> ```XML
> 
> mod state;
> pub use crate::state::*;
> ```

The `state` module only has a single type. So this is fine. But otherwise I suggest we stop re-exporting everything from all modules like this. The main namespace of this crate is growing pretty big. Having a bit of a tree structure would probably clean it up a bit. But again, not important here since it's only one item.
___
*[`src/lib.rs` line 188 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UIG9A9Yv2I00IR6J_:-O2UIG9A9Yv2I00IR6Ja:bv7l7bj) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/lib.rs#L188)):*
> ```XML
>             InvalidAddressFamily(reason) => write!(f, "Invalid address family ({reason})"),
>             InvalidDirection(reason) => write!(f, "Invalid direction ({reason})"),
>             InvalidTransportProtocol(reason) => write!(f, "Invalid transport protocol ({reason})"),
> ```

I think we should use a better name than `reason` here. These are not reasons. These are `address_family`, `direction` and `protocol` respectively.
___
*[`src/lib.rs` line 436 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UJ8N60x9X91nHHbkF:-O2UJ8N60x9X91nHHbkG:bwrj62k) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/lib.rs#L436)):*
> ```XML
>         setup_pfioc_state_kill(state.as_raw(), &mut pfioc_state_kill);
>         ioctl_guard!(ffi::pf_kill_states(self.fd(), &mut pfioc_state_kill))?;
>         // psk_af holds the number of killed states, but it should be zero
> ```

Why zero? Would it not match zero or one states? Zero if the state was already gone at the time of issuing this call, or one if it was removed?
___
*[`src/lib.rs` line 445 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UJf3UEH8s9HhtR4XI:-O2UJf3UEH8s9HhtR4XJ:b-yrbj9w) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/lib.rs#L445)):*
> ```XML
>         if num_states > 0 {
>             let (mut pfioc_states, pfsync_states) = setup_pfioc_states(num_states);
>             ioctl_guard!(ffi::pf_get_states(self.fd(), &mut pfioc_states))?;
> ```

Does this have a race? What happens if the number of states changes between the call to get number of states and the syscall to get the states?

Not fully related to this PR, but I noticed it now. Can we improve it to have retry logic or in some other way not fail in this way? Once we start using this feature to list and kill states we will be calling this method much more often, and be more likely to trigger the race, if there is one.
___
*[`src/state.rs` line 8 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UOqHP0L3UlywQ1UMQ:-O2UOqHP0L3UlywQ1UMR:b-py2dut) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/state.rs#L8)):*
> ```XML
> 
> /// PF connection state created by a stateful rule
> #[derive(Clone)]
> ```

`Debug` would be nice. I'm not sure how it would be automatically implemented, but good practice to have `Debug` on all public types.
___
*[`src/state.rs` line 25 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UP2qz8YzicXbiHu-M:-O2UP2qz8YzicXbiHu-N:bx1rw3c) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/state.rs#L25)):*
> ```XML
>     /// Return the transport protocol for this state
>     pub fn proto(&self) -> Result<Proto> {
>         Proto::try_from(self.sync_state.direction)
> ```

Typo? You pass in `sync_state.direction` and not the proto. Something we could catch with a unit test! Can you consider adding unit tests for this type? That would also help to make sure the endianness ninjaing in `parse_address` is correct and stays correct during refactoring.
___
*[`src/state.rs` line 54 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UPrVIBXZ_Jf01Tyvk:-O2UPrVIBXZ_Jf01Tyvl:b-snugr5) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/state.rs#L54)):*
> ```XML
>         _ => return Err(Error::from(ErrorInternal::InvalidAddressFamily(family))),
>     };
>     let port = unsafe { host.xport.port }.to_be();
> ```

Should this not be `from_be`? :thinking:  Is `host.xport.port` not stored in big endian? `SocketAddr::new` below wants the port in native-endianness.
___
*[`src/rule/direction.rs` line 36 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UKVvJC8pjNCDyk0cF:-O2UKVvJC8pjNCDyk0cG:bziikaq) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/rule/direction.rs#L36)):*
> ```XML
>         const INOUT: u8 = ffi::pfvar::PF_INOUT as u8;
>         const IN: u8 = ffi::pfvar::PF_IN as u8;
>         const OUT: u8 = ffi::pfvar::PF_OUT as u8;
> ```

We should probably not duplicate these. They are already defined and casted above.

Can we set `#[repr(u8)]` on the enum and assign these constants directly on the Rust variants? Then we can simply use our own enum when converting/matching.

Same goes for the other enums you implement `TryFrom<u8>` in this PR. Now when we go both ways, we should probably find a way to not duplicate a lot of FFI constants and their casting. Since your PR goes from needing them in a single place to two places, this work sort of lands on this PR.


<!-- Sent from Reviewable.io -->

2024-07-23 11:57 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/106)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @dlon)

___
*[`src/lib.rs` line 435 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2US2GEA2Z_NR4BxWSE:-O2US2GEA2Z_NR4BxWSF:b-89opfm) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/lib.rs#L435)):*
> ```XML
>         let mut pfioc_state_kill = unsafe { mem::zeroed::<ffi::pfvar::pfioc_state_kill>() };
>         setup_pfioc_state_kill(state.as_raw(), &mut pfioc_state_kill);
>         ioctl_guard!(ffi::pf_kill_states(self.fd(), &mut pfioc_state_kill))?;
> ```

Was it possible to use some kind of ID from the state? To ensure we only remove one state, and not all matching states? :thinking: 


<!-- Sent from Reviewable.io -->

2024-07-23 16:24 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/106)* status: 2 of 11 files reviewed, 8 unresolved discussions (waiting on @faern)

___
*[`src/lib.rs` line 435 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2US2GEA2Z_NR4BxWSE:-O2UXswu104AvB_A4AKo:b-i3hnma) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/lib.rs#L435)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Was it possible to use some kind of ID from the state? To ensure we only remove one state, and not all matching states? :thinking:
</blockquote></details>

I looked into it and DIOCKILLSTATES does not check any kind of state ID: https://github.com/apple/darwin-xnu/blob/main/bsd/net/pf_ioctl.c#L3403

But I believe a `(interface, protocol, local IP, local port, remote IP, remote port)` tuple will be unique anyway?
___
*[`src/lib.rs` line 436 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UJ8N60x9X91nHHbkF:-O2VNtam8hqfG7bXKojv:b423gd2) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/lib.rs#L436)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why zero? Would it not match zero or one states? Zero if the state was already gone at the time of issuing this call, or one if it was removed?
</blockquote></details>

I removed the comment, since we don't even refer to the field.
___
*[`src/state.rs` line 8 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UOqHP0L3UlywQ1UMQ:-O2VO0gV8iftWoMymBWC:b-vw7nk5) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/state.rs#L8)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

`Debug` would be nice. I'm not sure how it would be automatically implemented, but good practice to have `Debug` on all public types.
</blockquote></details>

Unfortunately, `pfsync_state` contains unions, so the `Debug` macro didn't work. I reran bindgen with `--disable-untagged-union`. But the output is not particularly useful, IMO. Maybe just manually implementing `Debug` would be fine?
___
*[`src/state.rs` line 54 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UPrVIBXZ_Jf01Tyvk:-O2UjzRb5VCHfu0S1pOB:b-3hz2h7) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/state.rs#L54)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Should this not be `from_be`? :thinking:  Is `host.xport.port` not stored in big endian? `SocketAddr::new` below wants the port in native-endianness.
</blockquote></details>

You're right! Fixed.


<!-- Sent from Reviewable.io -->

2024-07-23 20:31 UTC, faern reviewed
> Reviewed 1 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/106)* status: 3 of 11 files reviewed, 6 unresolved discussions (waiting on @dlon)

___
*[`src/lib.rs` line 435 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2US2GEA2Z_NR4BxWSE:-O2WDSBYCigUx6GKjPnR:bu7f564) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/lib.rs#L435)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

I looked into it and DIOCKILLSTATES does not check any kind of state ID: https://github.com/apple/darwin-xnu/blob/main/bsd/net/pf_ioctl.c#L3403

But I believe a `(interface, protocol, local IP, local port, remote IP, remote port)` tuple will be unique anyway?
</blockquote></details>

Ok. Maybe it will. I have not dived into the details. Given your question mark you don't sound sure either :wink: But yeah, at least I guess we can assume only states matching all the fields. If there happens to be >1 state matching then at least the user already told us to remove those state(s). So I guess it's fine. Let's move on!
___
*[`src/lib.rs` line 431 at r3](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2WE_-P4BRnHSwKojO1:-O2WE_-P4BRnHSwKojO2:b3tyqle) ([raw file](https://github.com/mullvad/pfctl-rs/blob/d4d2b7683d072b07e09b0bb85565081f004f0103/src/lib.rs#L431)):*
Please add information on how to obtain a `&State`. Otherwise it's hard to know how to use this method. Something like:

> /// Remove the specified state.
> ///
> /// All current states can be obtained via [`get_states`].
___
*[`src/state.rs` line 8 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UOqHP0L3UlywQ1UMQ:-O2WFn8X1NXHwTUYfyf9:b-d87vkh) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/state.rs#L8)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Unfortunately, `pfsync_state` contains unions, so the `Debug` macro didn't work. I reran bindgen with `--disable-untagged-union`. But the output is not particularly useful, IMO. Maybe just manually implementing `Debug` would be fine?
</blockquote></details>

I think we should revert the changes to the FFI. It became a very large change, and primarily just more complicated types. Either leave `Debug` out, or implement it manually IMO.
___
*[`src/state.rs` line 56 at r3](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2WHNnS7IBR-_OgX0JD:-O2WHNnS7IBR-_OgX0JE:bc4fbb8) ([raw file](https://github.com/mullvad/pfctl-rs/blob/d4d2b7683d072b07e09b0bb85565081f004f0103/src/state.rs#L56)):*
> ```XML
>         _ => return Err(Error::from(ErrorInternal::InvalidAddressFamily(family))),
>     };
>     let port = u16::from_be(unsafe { *host.xport.port.as_ref() });
> ```

This function has a lot of `unsafe`. But no safety docs. Is it possible to cause UB by calling this function with carefully crafted bad arguments? If so, the function needs to be `unsafe`.


<!-- Sent from Reviewable.io -->

2024-07-23 20:33 UTC, faern reviewed
> Reviewed 1 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/106)* status: 4 of 11 files reviewed, 7 unresolved discussions (waiting on @dlon)

___
*[`generate_bindings.sh` line 25 at r3](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2WHutpAowDADC7BJin:-O2WHutpAowDADC7BJio:b-xklmme) ([raw file](https://github.com/mullvad/pfctl-rs/blob/d4d2b7683d072b07e09b0bb85565081f004f0103/generate_bindings.sh#L25)):*
> ```Shell
>     --allowlist-var PFRULE_.* \
>     --default-enum-style rust \
>     --disable-untagged-union \
> ```

I don't think we should change this unless we have a good reason. Currently it mostly looks like it messes a lot with the library code, for very little gain, if any.


<!-- Sent from Reviewable.io -->

2024-07-24 09:39 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/106)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @faern)

___
*[`src/lib.rs` line 92 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UIUUN2Ga-qzfx1z4a:-O2Z5jJj3lElAeCJbxFR:bf6lylp) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/lib.rs#L92)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The `state` module only has a single type. So this is fine. But otherwise I suggest we stop re-exporting everything from all modules like this. The main namespace of this crate is growing pretty big. Having a bit of a tree structure would probably clean it up a bit. But again, not important here since it's only one item.
</blockquote></details>

Agreed that we should not do this in general, but I think it's more important to be consistent. This would be a breaking change, though.
___
*[`src/lib.rs` line 188 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UIG9A9Yv2I00IR6J_:-O2YiDEC0m3Jd1HVRcqv:b-896fix) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/lib.rs#L188)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think we should use a better name than `reason` here. These are not reasons. These are `address_family`, `direction` and `protocol` respectively.
</blockquote></details>

Done.
___
*[`src/lib.rs` line 445 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UJf3UEH8s9HhtR4XI:-O2Z4iXAD4J-fq3_6Ujp:b-67pm7l) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/lib.rs#L445)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Does this have a race? What happens if the number of states changes between the call to get number of states and the syscall to get the states?

Not fully related to this PR, but I noticed it now. Can we improve it to have retry logic or in some other way not fail in this way? Once we start using this feature to list and kill states we will be calling this method much more often, and be more likely to trigger the race, if there is one.
</blockquote></details>

Yeah, this is definitely wrong! Retrying while the buffer is too small is also what `pfctl` does: https://github.com/openbsd/src/blob/master/sbin/pfctl/pfctl.c#L1047
___
*[`src/state.rs` line 8 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UOqHP0L3UlywQ1UMQ:-O2YjESFDjXr2Ba2aV_D:b-4ni3ju) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/state.rs#L8)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I think we should revert the changes to the FFI. It became a very large change, and primarily just more complicated types. Either leave `Debug` out, or implement it manually IMO.
</blockquote></details>

Added a manual implementation.
___
*[`src/state.rs` line 25 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UP2qz8YzicXbiHu-M:-O2VOcJpDUOYeE62iZS7:bppesd6) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/state.rs#L25)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Typo? You pass in `sync_state.direction` and not the proto. Something we could catch with a unit test! Can you consider adding unit tests for this type? That would also help to make sure the endianness ninjaing in `parse_address` is correct and stays correct during refactoring.
</blockquote></details>

This is now covered both by unit tests and the integration tests I've added.
___
*[`src/state.rs` line 56 at r3](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2WHNnS7IBR-_OgX0JD:-O2YvQXgAznlbbPqT0Z1:b1h3tc4) ([raw file](https://github.com/mullvad/pfctl-rs/blob/d4d2b7683d072b07e09b0bb85565081f004f0103/src/state.rs#L56)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This function has a lot of `unsafe`. But no safety docs. Is it possible to cause UB by calling this function with carefully crafted bad arguments? If so, the function needs to be `unsafe`.
</blockquote></details>

It should always be safe, because the struct is zero-initialized. But it's not always meaningful. Commented to clarify.
___
*[`src/rule/direction.rs` line 36 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UKVvJC8pjNCDyk0cF:-O2Z48FxEw9a2zJQEou3:b-896fix) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/rule/direction.rs#L36)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

We should probably not duplicate these. They are already defined and casted above.

Can we set `#[repr(u8)]` on the enum and assign these constants directly on the Rust variants? Then we can simply use our own enum when converting/matching.

Same goes for the other enums you implement `TryFrom<u8>` in this PR. Now when we go both ways, we should probably find a way to not duplicate a lot of FFI constants and their casting. Since your PR goes from needing them in a single place to two places, this work sort of lands on this PR.
</blockquote></details>

Done.
___
*[`generate_bindings.sh` line 25 at r3](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2WHutpAowDADC7BJin:-O2YhUpN75fDF5Fdrlex:bp3aow6) ([raw file](https://github.com/mullvad/pfctl-rs/blob/d4d2b7683d072b07e09b0bb85565081f004f0103/generate_bindings.sh#L25)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I don't think we should change this unless we have a good reason. Currently it mostly looks like it messes a lot with the library code, for very little gain, if any.
</blockquote></details>

Reverted.


<!-- Sent from Reviewable.io -->

2024-07-24 11:13 UTC, faern reviewed
> Reviewed 10 of 11 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/106)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[`src/lib.rs` line 445 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UJf3UEH8s9HhtR4XI:-O2ZJGh36Y9Z93dB4nVO:b-mly9gh) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/lib.rs#L445)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Yeah, this is definitely wrong! Retrying while the buffer is too small is also what `pfctl` does: https://github.com/openbsd/src/blob/master/sbin/pfctl/pfctl.c#L1047
</blockquote></details>

Ok. Let's leave that for a separate PR! But this needs fixing. I created an issue: https://github.com/mullvad/pfctl-rs/issues/109
___
*[`src/state.rs` line 25 at r2](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2UP2qz8YzicXbiHu-M:-O2ZMyEL40XmFR03L5Fz:b-ethmss) ([raw file](https://github.com/mullvad/pfctl-rs/blob/0809447e6c2879df2940a4a14dff41394566db76/src/state.rs#L25)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This is now covered both by unit tests and the integration tests I've added.
</blockquote></details>

Really nice!
___
*[`src/state.rs` line 56 at r3](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2WHNnS7IBR-_OgX0JD:-O2ZOUR708SqOsayNcN9:b27s2jl) ([raw file](https://github.com/mullvad/pfctl-rs/blob/d4d2b7683d072b07e09b0bb85565081f004f0103/src/state.rs#L56)):*
> because the struct is zero-initialized

This is not something this function guarantees. A function's safety contract has to be upheld by that function itself, not how it's called by others.

Maybe this is safe... What guarantees does Rust give about the unused memory of a union?

If I have
```rust
union Foo {
    small: u8,
    large: u128,
}
```
And I initialize a `Foo { small: 0 }`. Is it then safe to read `foo.large`? If so, this function is safe. Otherwise not. Because here we read `host.addr.pfa._v6addr`. This is not the smallest field in the enum, so what happens when someone calls `parse_address` with a `pfa` initialized to a smaller union variant than v6?
___
*[`src/rule/direction.rs` line 18 at r5](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2ZLSlpCPpFXJ7VpfP8:-O2ZLSlpCPpFXJ7VpfP9:bnpuzns) ([raw file](https://github.com/mullvad/pfctl-rs/blob/6d40bf7cbcbd484d201048a7a5be5bfaeed92501/src/rule/direction.rs#L18)):*
> ```XML
>     Any = ffi::pfvar::PF_INOUT as u32 as u8,
>     In = ffi::pfvar::PF_IN as u32 as u8,
>     Out = ffi::pfvar::PF_OUT as u32 as u8,
> ```

Why must this be cast twice? The code that is removed in this PR did not have to do the double cast :thinking: 
___
*[`tests/states.rs` line 161 at r5](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2ZMYcPA-i7uczoXPvX:-O2ZMYcPA-i7uczoXPvY:b12wput) ([raw file](https://github.com/mullvad/pfctl-rs/blob/6d40bf7cbcbd484d201048a7a5be5bfaeed92501/tests/states.rs#L161)):*
> ```XML
>         .expect("Could not obtain states")
>         .into_iter()
>         .filter_map(|state| ExpectedState::try_from(state).ok()).collect::<Vec<_>>();
> ```

This construct is nice! May I suggest you use it above in the previous `pf.get_states()` also? That makes the code inside the for loop simpler (currently pretty hard to read it all since it does a lot in one go)


<!-- Sent from Reviewable.io -->

2024-07-24 11:19 UTC, faern reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/106)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon)

___
*[`src/state.rs` line 56 at r3](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2WHNnS7IBR-_OgX0JD:-O2ZSaVmDP_v-DfZxq65:b-52jlxt) ([raw file](https://github.com/mullvad/pfctl-rs/blob/d4d2b7683d072b07e09b0bb85565081f004f0103/src/state.rs#L56)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

> because the struct is zero-initialized

This is not something this function guarantees. A function's safety contract has to be upheld by that function itself, not how it's called by others.

Maybe this is safe... What guarantees does Rust give about the unused memory of a union?

If I have
```rust
union Foo {
    small: u8,
    large: u128,
}
```
And I initialize a `Foo { small: 0 }`. Is it then safe to read `foo.large`? If so, this function is safe. Otherwise not. Because here we read `host.addr.pfa._v6addr`. This is not the smallest field in the enum, so what happens when someone calls `parse_address` with a `pfa` initialized to a smaller union variant than v6?
</blockquote></details>

Valgrind does *not* like the following program:

```rust
fn main() {
    let foo = Foo { small: 123 };
    println!("{}", unsafe { foo.large });
}

union Foo {
    small: u8,
    large: u128,
}
```
But it does not trigger any errors if `foo` is initialized as `Foo { large: 123 };`. So yeah, The current implementation of `parse_address` *is unsafe* as far as I can tell.


<!-- Sent from Reviewable.io -->

2024-07-24 12:11 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/106)* status: 10 of 11 files reviewed, 5 unresolved discussions (waiting on @dlon)

___
*[`src/state.rs` line 44 at r6](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2Zcv2BBj1y89bcOBX3:-O2Zcv2BBj1y89bcOBX4:b-4pldc7) ([raw file](https://github.com/mullvad/pfctl-rs/blob/85267af323109d678bdc6addd0c395445d4d512d/src/state.rs#L44)):*
Good documentation on `parse_address`!

But now this method makes a lot of assumptions that has nothing with `local_address` to do. When you (as discussed AFK) add unsafety to `State::new` and explain why it's unsafe, then this safety documentation can be something like:

> If the safety contract in `State::new` is upheld, `sync_state.lan` is guaranteed to be initialized according to the `sync_state.af_lan` family.
___
*[`src/state.rs` line 131 at r6](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2Zc_Mo8Mg_qBTsMFYE:-O2Zc_Mo8Mg_qBTsMFYF:bj9yg38) ([raw file](https://github.com/mullvad/pfctl-rs/blob/85267af323109d678bdc6addd0c395445d4d512d/src/state.rs#L131)):*
> ```XML
>         let family = u8::from(AddrFamily::Ipv6);
> 
>         assert_matches!(unsafe { parse_address(family, host) }, Ok(addr) if addr == SocketAddr::new(EXPECTED_IP.into(), EXPECTED_PORT));
> ```

Nit. But instead of making this line super long. I would probably have a line before it with `let address = unsafe { parse_address(family, host) }.unwrap();`. This splits the complexity into two statements.


<!-- Sent from Reviewable.io -->

2024-07-24 12:38 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/106)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[`src/lib.rs` line 431 at r3](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2WE_-P4BRnHSwKojO1:-O2ZaQh-1MZ0UroyRPRh:b-896fix) ([raw file](https://github.com/mullvad/pfctl-rs/blob/d4d2b7683d072b07e09b0bb85565081f004f0103/src/lib.rs#L431)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Please add information on how to obtain a `&State`. Otherwise it's hard to know how to use this method. Something like:

> /// Remove the specified state.
> ///
> /// All current states can be obtained via [`get_states`].
</blockquote></details>

Done.
___
*[`src/state.rs` line 44 at r6](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2Zcv2BBj1y89bcOBX3:-O2Zhc5uCvjcaNfrbJK6:b-vi7nsk) ([raw file](https://github.com/mullvad/pfctl-rs/blob/85267af323109d678bdc6addd0c395445d4d512d/src/state.rs#L44)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Good documentation on `parse_address`!

But now this method makes a lot of assumptions that has nothing with `local_address` to do. When you (as discussed AFK) add unsafety to `State::new` and explain why it's unsafe, then this safety documentation can be something like:

> If the safety contract in `State::new` is upheld, `sync_state.lan` is guaranteed to be initialized according to the `sync_state.af_lan` family.
</blockquote></details>

Done. Would it be acceptable to simply state that the object passed to `new` must be zero-initialized? I think that covers all cases without being overly verbose.
___
*[`src/state.rs` line 131 at r6](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2Zc_Mo8Mg_qBTsMFYE:-O2Zj9ih38eKmTDKjetm:b-2vryu4) ([raw file](https://github.com/mullvad/pfctl-rs/blob/85267af323109d678bdc6addd0c395445d4d512d/src/state.rs#L131)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nit. But instead of making this line super long. I would probably have a line before it with `let address = unsafe { parse_address(family, host) }.unwrap();`. This splits the complexity into two statements.
</blockquote></details>

Done. Much better.
___
*[`src/rule/direction.rs` line 18 at r5](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2ZLSlpCPpFXJ7VpfP8:-O2ZiadaDBABWV3wDBYQ:b-896fix) ([raw file](https://github.com/mullvad/pfctl-rs/blob/6d40bf7cbcbd484d201048a7a5be5bfaeed92501/src/rule/direction.rs#L18)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why must this be cast twice? The code that is removed in this PR did not have to do the double cast :thinking:
</blockquote></details>

Done.
___
*[`tests/states.rs` line 161 at r5](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2ZMYcPA-i7uczoXPvX:-O2ZidjT5xcIc0ceotE0:bpnqdp1) ([raw file](https://github.com/mullvad/pfctl-rs/blob/6d40bf7cbcbd484d201048a7a5be5bfaeed92501/tests/states.rs#L161)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This construct is nice! May I suggest you use it above in the previous `pf.get_states()` also? That makes the code inside the for loop simpler (currently pretty hard to read it all since it does a lot in one go)
</blockquote></details>

I didn't do that since the original state is needed for `kill_state`.


<!-- Sent from Reviewable.io -->

2024-07-24 13:00 UTC, faern approved these changes
> Reviewed 2 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/pfctl-rs/106)* status: all files reviewed, 1 unresolved discussion

___
*[`src/state.rs` line 44 at r6](https://reviewable.io/reviews/mullvad/pfctl-rs/106#-O2Zcv2BBj1y89bcOBX3:-O2ZluQpEYlhKV5jSY4U:bhudbcw) ([raw file](https://github.com/mullvad/pfctl-rs/blob/85267af323109d678bdc6addd0c395445d4d512d/src/state.rs#L44)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. Would it be acceptable to simply state that the object passed to `new` must be zero-initialized? I think that covers all cases without being overly verbose.
</blockquote></details>

Much simpler! Let's keep it simple :P


<!-- Sent from Reviewable.io -->

2024-07-24 14:32 UTC, merged